# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Separan.Core
PackageVersion: 1.1.2
InstallerType: inno
Scope: user
UpgradeBehavior: install
ProductCode: '{EDAFDCD7-2243-4A5F-BC98-09B0F66F2A32}_is1'
ReleaseDate: 2026-09-29
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mocchii2/Separan/releases/download/v1.1.2/separan-installer.exe
  InstallerSha256: A76F618A48238DB01D4592958C6A37D0341B8B37D8FD6EC501C8458BC3B4A00D
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART
    SilentWithProgress: /SILENT /NORESTART
ManifestType: installer
ManifestVersion: 1.12.0