# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Separan.Core
PackageVersion: 1.1.1
InstallerType: inno
Scope: user
UpgradeBehavior: install
ProductCode: '{EDAFDCD7-2243-4A5F-BC98-09B0F66F2A32}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mocchii2/Separan/releases/download/v1.1.1/separan-installer.exe
  InstallerSha256: 6CDC12C4C5395D3B9F717C0A4306A5FB93FE1DBFDC27B052C4AE141C0FE0BCD5
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART
    SilentWithProgress: /SILENT /NORESTART
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-27
