# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Separan.Core
PackageVersion: 1.1.1
InstallerType: inno
Scope: user
UpgradeBehavior: install
ProductCode: '{EDAFDCD7-2243-4A5F-BC98-09B0F66F2A32}_is1'
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mocchii2/Separan/releases/download/v1.1.1/separan-installer.exe
  InstallerSha256: F9CE4310F4A2E97F3A5FEBEBB78C077DC34499944395C39458617FD5793FC1BC
  InstallerSwitches:
    Silent: /VERYSILENT /NORESTART
    SilentWithProgress: /SILENT /NORESTART
ManifestType: installer
ManifestVersion: 1.12.0
