# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Separan.Core
PackageVersion: 1.1.1
PackageLocale: en-US
Publisher: Separan
PublisherUrl: https://github.com/mocchii2/Separan
PackageName: Separan Core
PackageUrl: https://github.com/mocchii2/Separan
License: Apache-2.0
LicenseUrl: https://github.com/mocchii2/Separan/blob/main/LICENSE
ShortDescription: Separan Core native C command-line runtime.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
